"""Initial migration

Revision ID: e924d89f2646
Revises: 
Create Date: 2025-09-06 02:41:17.995981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e924d89f2646'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'service_areas',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tenants', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_tenants_phone'), 'tenants', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_phone'), table_name='tenants')
    op.alter_column('tenants', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('agents', 'service_areas',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
