"""create all tables

Revision ID: ee0498a421f0
Revises: e924d89f2646
Create Date: 2025-09-06 17:46:10.978635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee0498a421f0'
down_revision: Union[str, Sequence[str], None] = 'e924d89f2646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'service_areas',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'service_areas',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
